

[printer Voron 2.4]
titlebar_items: chamber

#####################################################################
# Klipper Menu on Main screen
#####################################################################

[menu __main custom]
name: Printer Prep
icon: klipper

#####################################################################
# Tool selection
#####################################################################

[menu __main custom tool_t0]
name: Select T0
icon: extrude
method: printer.gcode.script
params: {"script":"T0"}

[menu __main custom tool_t1]
name: Select T1
icon: extrude
method: printer.gcode.script
params: {"script":"T1"}

[menu __main custom tool_t2]
name: Select T2
icon: extrude
method: printer.gcode.script
params: {"script":"T2"}

[menu __main custom tool_t3]
name: Select T3
icon: extrude
method: printer.gcode.script
params: {"script":"T3"}

[menu __main custom tool_t4]
name: Select T4
icon: extrude
method: printer.gcode.script
params: {"script":"T4"}

#####################################################################
# Filament / buffer workflow
#####################################################################

[menu __main custom buffer_arm]
name: Arm Buffer
icon: refresh
method: printer.gcode.script
params: {"script":"BUFFER_ARM_ACTIVE_TOOL RESET_OVERFILL=1"}

[menu __main custom buffer_auto]
name: Buffer Auto
icon: refresh
method: printer.gcode.script
params: {"script":"BUFFER_ARM_ACTIVE_TOOL"}

# screen_on_devices: Auto Lights
# screen_off_devices: Auto Lights

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = astech-dark
#~# screen_blanking_printing = 14400
#~# confirm_estop = True
#~# print_sort_dir = date_desc
#~# 
#~# [displayed_macros Printer]
#~# g32 = False
#~# m300 = False
#~# m600 = False
#~# print_end = False
#~# print_start = False
#~# pause_resume = False
#~# purge_line = False
#~# test_speed = False
#~# resume = False
#~# wipe_nozzle = False
#~# stop_beeping = False
#~# smart_park = False
#~# voron_purge = False
#~#
